"""
maintenance/scheduler.py
========================
Generates all systemd service and timer units for scheduled maintenance.
Implements the dependency chain: SMART scan → BTRFS defrag (with 06:00 cutoff).

Chain logic:
  1. SMART long scan starts at 22:00 on day 1 of each month
  2. On completion, a lockfile is written: /var/run/server-suite/smart-done
  3. BTRFS defrag timer checks at 22:00 — if smart-done exists, runs defrag
  4. If smart scan is still running at 06:00 next morning, defrag reschedules
     itself to 22:00 that night via a oneshot catch-up timer
  5. BTRFS scrub runs on day 8 of each month (after defrag window)
  6. Health check (disk temp, space, RAID status) runs daily at 08:00
"""

import os
import subprocess
from pathlib import Path
from rich.console import Console

console = Console()
DRY_RUN = os.environ.get("DRY_RUN", "0") == "1"

SYSTEMD_DIR    = Path("/etc/systemd/system")
SUITE_DIR      = Path("/opt/server-suite")
SCRIPTS_DIR    = SUITE_DIR / "scripts"
LOG_DIR        = Path("/var/log/server-suite")
LOCKFILE_DIR   = Path("/var/run/server-suite")


def _run(cmd: list, timeout: int = 30) -> tuple[int, str, str]:
    if DRY_RUN:
        console.print(f"  [dim][DRY RUN] {' '.join(cmd)}[/dim]")
        return 0, "", ""
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        return r.returncode, r.stdout.strip(), r.stderr.strip()
    except Exception as e:
        return -1, "", str(e)


def _write(path: Path, content: str, mode: int = 0o644):
    """Write a file, respecting DRY_RUN."""
    if DRY_RUN:
        console.print(f"  [dim][DRY RUN] Would write: {path}[/dim]")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    os.chmod(path, mode)


class MaintenanceScheduler:
    """Generates and installs all systemd maintenance units."""

    def __init__(self, suite_dir: Path = SUITE_DIR, notify_email: str = ""):
        self.suite_dir   = Path(suite_dir)
        self.scripts_dir = self.suite_dir / "scripts"
        self.notify_email = notify_email

    # -----------------------------------------------------------------------
    # Public entry point
    # -----------------------------------------------------------------------

    def setup_all(self, config: dict) -> bool:
        """Generate and install all maintenance units."""
        console.print("\n[bold cyan]Setting Up Maintenance Schedules[/bold cyan]\n")

        self.notify_email = (
            config.get("notifications", {}).get("email") or
            config.get("notify_email", "root")
        )

        # Ensure directories exist
        for d in [self.scripts_dir, LOG_DIR]:
            if not DRY_RUN:
                d.mkdir(parents=True, exist_ok=True)

        roles = config.get("roles", {})
        has_storage = "storage" in roles or bool(roles)

        # Always generate health check
        self._generate_health_check()
        self._install_health_check_timer()

        # Storage-related maintenance
        if has_storage:
            self._generate_smart_scan(config)
            self._generate_btrfs_defrag(config)
            self._generate_btrfs_scrub(config)
            self._install_smart_timer()
            self._install_defrag_timer()
            self._install_scrub_timer()
            self._install_defrag_catchup_timer()

        # Log rotation
        self._configure_logrotate()

        # Reload systemd
        _run(["systemctl", "daemon-reload"])

        # Enable all timers
        self._enable_timers(has_storage)

        console.print("\n[green]Maintenance schedules installed ✓[/green]")
        self._print_schedule_summary(has_storage)
        return True

    # -----------------------------------------------------------------------
    # SMART scan script + units
    # -----------------------------------------------------------------------

    def _generate_smart_scan(self, config: dict):
        """Generate the SMART long scan shell script."""
        mount_point = config.get("storage", {}).get("mount_point", "/mnt/data")
        script = f"""#!/usr/bin/env bash
# =============================================================================
# Server Suite — SMART Long Scan
# Generated by server-suite maintenance scheduler
# Runs monthly. Reports emailed to: {self.notify_email}
# =============================================================================
set -euo pipefail

SUITE_DIR="{self.suite_dir}"
LOG_FILE="{LOG_DIR}/smart-scan.log"
LOCKFILE="{LOCKFILE_DIR}/smart-running"
DONE_FILE="{LOCKFILE_DIR}/smart-done"
NOTIFY_EMAIL="{self.notify_email}"
HOSTNAME="$(hostname -f)"
SCAN_START="$(date '+%Y-%m-%d %H:%M:%S')"

# ---- Helpers ----------------------------------------------------------------
log()   {{ echo "[$( date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"; }}
error() {{ log "ERROR: $*"; }}

# ---- Pre-flight -------------------------------------------------------------
mkdir -p "{LOCKFILE_DIR}" "{LOG_DIR}"

# Prevent concurrent runs
if [[ -f "$LOCKFILE" ]]; then
    OLD_PID=$(cat "$LOCKFILE" 2>/dev/null || echo "")
    if [[ -n "$OLD_PID" ]] && kill -0 "$OLD_PID" 2>/dev/null; then
        log "SMART scan already running (PID $OLD_PID). Exiting."
        exit 0
    fi
fi

echo "$$" > "$LOCKFILE"
rm -f "$DONE_FILE"

trap 'rm -f "$LOCKFILE"; log "SMART scan interrupted."' EXIT INT TERM

log "===== SMART Long Scan Started ====="
log "Host: $HOSTNAME"

# ---- Detect all drives ------------------------------------------------------
DRIVES=()
while IFS= read -r dev; do
    DRIVES+=("$dev")
done < <(lsblk -d -o NAME,TYPE --noheadings | awk '$2=="disk" {{print "/dev/"$1}}')

if [[ ${{#DRIVES[@]}} -eq 0 ]]; then
    log "No drives found. Exiting."
    exit 1
fi

log "Found ${{#DRIVES[@]}} drive(s): ${{DRIVES[*]}}"

# ---- Run long tests (non-blocking start) ------------------------------------
log "Starting long self-tests on all drives..."
FAILED_DRIVES=()
PASSED_DRIVES=()
REPORT_DATA=""

for DRIVE in "${{DRIVES[@]}}"; do
    log "Initiating long test on $DRIVE..."
    smartctl -t long "$DRIVE" >> "$LOG_FILE" 2>&1 || true
done

# ---- Poll for completion ----------------------------------------------------
log "Waiting for tests to complete (this may take several hours)..."
MAX_WAIT=28800   # 8 hours max
POLL_INTERVAL=60
ELAPSED=0

while [[ $ELAPSED -lt $MAX_WAIT ]]; do
    ALL_DONE=true
    for DRIVE in "${{DRIVES[@]}}"; do
        STATUS=$(smartctl -a "$DRIVE" 2>/dev/null | grep -i "self-test execution status" | head -1 || echo "")
        if echo "$STATUS" | grep -qi "in progress"; then
            ALL_DONE=false
            break
        fi
    done
    if $ALL_DONE; then
        break
    fi
    sleep $POLL_INTERVAL
    ELAPSED=$((ELAPSED + POLL_INTERVAL))
    if (( ELAPSED % 1800 == 0 )); then
        log "Still running... ($((ELAPSED/3600))h $((ELAPSED%3600/60))m elapsed)"
    fi
done

# ---- Collect results --------------------------------------------------------
log "Collecting results..."
OVERALL_STATUS="PASSED"

for DRIVE in "${{DRIVES[@]}}"; do
    MODEL=$(smartctl -i "$DRIVE" 2>/dev/null | grep -E "^(Device Model|Model Number)" | head -1 | awk -F: '{{print $2}}' | xargs)
    SERIAL=$(smartctl -i "$DRIVE" 2>/dev/null | grep "Serial Number" | awk -F: '{{print $2}}' | xargs)
    HEALTH=$(smartctl -H "$DRIVE" 2>/dev/null | grep -i "overall-health" | awk -F: '{{print $2}}' | xargs)
    TEMP=$(smartctl -A "$DRIVE" 2>/dev/null | grep -E "^[[:space:]]*(190|194)[[:space:]]" | awk '{{print $NF}}' | head -1)
    POH=$(smartctl -A "$DRIVE" 2>/dev/null | grep -E "^[[:space:]]*9[[:space:]]" | awk '{{print $NF}}' | head -1)
    REALLOC=$(smartctl -A "$DRIVE" 2>/dev/null | grep -E "^[[:space:]]*5[[:space:]]" | awk '{{print $NF}}' | head -1 || echo "0")
    PENDING=$(smartctl -A "$DRIVE" 2>/dev/null | grep -E "^[[:space:]]*197[[:space:]]" | awk '{{print $NF}}' | head -1 || echo "0")
    UNCORR=$(smartctl -A "$DRIVE" 2>/dev/null | grep -E "^[[:space:]]*198[[:space:]]" | awk '{{print $NF}}' | head -1 || echo "0")
    LAST_TEST=$(smartctl -l selftest "$DRIVE" 2>/dev/null | grep -E "^[[:space:]]*#[[:space:]]*1" | head -1)

    DRIVE_STATUS="PASSED"
    WARNINGS=""
    if [[ "$HEALTH" != *"PASSED"* ]] && [[ "$HEALTH" != *"OK"* ]]; then
        DRIVE_STATUS="FAILED"
        OVERALL_STATUS="FAILED"
    fi
    if [[ "${{REALLOC:-0}}" -gt 0 ]]; then
        WARNINGS+="  ⚠ Reallocated sectors: $REALLOC\\n"
    fi
    if [[ "${{PENDING:-0}}" -gt 0 ]]; then
        WARNINGS+="  ⚠ Pending sectors: $PENDING\\n"
        OVERALL_STATUS="WARNING"
    fi
    if [[ "${{UNCORR:-0}}" -gt 0 ]]; then
        WARNINGS+="  ⚠ Uncorrectable errors: $UNCORR\\n"
        OVERALL_STATUS="FAILED"
    fi

    if [[ "$DRIVE_STATUS" == "PASSED" ]]; then
        PASSED_DRIVES+=("$DRIVE")
    else
        FAILED_DRIVES+=("$DRIVE")
    fi

    REPORT_DATA+="DRIVE:$DRIVE|MODEL:${{MODEL:-Unknown}}|SERIAL:${{SERIAL:-Unknown}}|HEALTH:${{HEALTH:-Unknown}}|TEMP:${{TEMP:-N/A}}|POH:${{POH:-N/A}}|REALLOC:${{REALLOC:-0}}|PENDING:${{PENDING:-0}}|UNCORR:${{UNCORR:-0}}|STATUS:$DRIVE_STATUS|WARNINGS:$WARNINGS\\n"
    log "  $DRIVE (${{MODEL:-?}}): $DRIVE_STATUS | Temp: ${{TEMP:-?}}°C | POH: ${{POH:-?}}h"
done

log "Overall result: $OVERALL_STATUS"

# ---- Send email report ------------------------------------------------------
if command -v python3 &>/dev/null; then
    python3 - <<PYEOF
import sys, os
sys.path.insert(0, "${{SUITE_DIR}}")
from core.notifications import NotificationManager
from pathlib import Path

nm = NotificationManager(Path("${{SUITE_DIR}}"))

raw = r\"\"\"{REPORT_DATA}\"\"\"
drives = []
for line in raw.strip().splitlines():
    if not line.strip():
        continue
    d = {{}}
    for part in line.split("|"):
        if ":" in part:
            k, _, v = part.partition(":")
            d[k.lower()] = v
    if d:
        drives.append(d)

html = nm.render_smart_report(drives, "${{HOSTNAME}}")
subject = f"SMART Scan: ${{OVERALL_STATUS}} — ${{HOSTNAME}}"
nm.send_report(subject, html, recipient="${{NOTIFY_EMAIL}}")
print("Email report sent.")
PYEOF
fi

# ---- Write done lockfile ----------------------------------------------------
SCAN_END="$(date '+%Y-%m-%d %H:%M:%S')"
echo "$SCAN_END" > "$DONE_FILE"
rm -f "$LOCKFILE"

log "===== SMART Scan Complete: $OVERALL_STATUS ====="
log "Duration: started $SCAN_START, ended $SCAN_END"

# Exit code reflects overall health
if [[ "$OVERALL_STATUS" == "FAILED" ]]; then
    exit 2
elif [[ "$OVERALL_STATUS" == "WARNING" ]]; then
    exit 1
fi
exit 0
"""
        _write(self.scripts_dir / "smart-scan.sh", script, mode=0o750)
        console.print("  [dim]Generated: smart-scan.sh ✓[/dim]")

    # -----------------------------------------------------------------------
    # BTRFS defrag script + units
    # -----------------------------------------------------------------------

    def _generate_btrfs_defrag(self, config: dict):
        """Generate the BTRFS defrag shell script."""
        mount_point = config.get("storage", {}).get("mount_point", "/mnt/data")
        script = f"""#!/usr/bin/env bash
# =============================================================================
# Server Suite — BTRFS Defragmentation
# Generated by server-suite maintenance scheduler
# Runs monthly after SMART scan. Reports emailed to: {self.notify_email}
# =============================================================================
set -euo pipefail

SUITE_DIR="{self.suite_dir}"
MOUNT_POINT="{mount_point}"
LOG_FILE="{LOG_DIR}/btrfs-defrag.log"
SMART_DONE_FILE="{LOCKFILE_DIR}/smart-done"
SMART_LOCK_FILE="{LOCKFILE_DIR}/smart-running"
DEFRAG_LOCK="{LOCKFILE_DIR}/defrag-running"
NOTIFY_EMAIL="{self.notify_email}"
HOSTNAME="$(hostname -f)"
START_TIME="$(date '+%Y-%m-%d %H:%M:%S')"
CURRENT_HOUR=$(date +%H)
CURRENT_MIN=$(date +%M)

log()   {{ echo "[$( date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"; }}
error() {{ log "ERROR: $*"; }}

mkdir -p "{LOCKFILE_DIR}" "{LOG_DIR}"

# ---- Check if SMART scan has completed -------------------------------------
# If SMART is still running AND it's past 06:00, reschedule for tonight
if [[ -f "$SMART_LOCK_FILE" ]]; then
    if [[ -n "$(cat "$SMART_LOCK_FILE" 2>/dev/null)" ]] && \\
       kill -0 "$(cat "$SMART_LOCK_FILE" 2>/dev/null)" 2>/dev/null; then
        log "SMART scan still running."
        if [[ "$CURRENT_HOUR" -ge 6 ]]; then
            log "It is past 06:00. Scheduling defrag catch-up for 22:00 tonight."
            systemctl start server-suite-defrag-catchup.timer 2>/dev/null || true
            exit 0
        else
            log "Waiting for SMART scan to complete before proceeding..."
            # Wait up to 30 minutes
            for i in $(seq 1 30); do
                sleep 60
                if [[ ! -f "$SMART_LOCK_FILE" ]]; then
                    break
                fi
            done
        fi
    fi
fi

# If no smart-done file, SMART either didn't run or failed — proceed anyway
# but log the anomaly
if [[ ! -f "$SMART_DONE_FILE" ]]; then
    log "WARNING: SMART done file not found — proceeding with defrag anyway."
fi

# ---- Prevent concurrent runs -----------------------------------------------
if [[ -f "$DEFRAG_LOCK" ]]; then
    OLD_PID=$(cat "$DEFRAG_LOCK" 2>/dev/null || echo "")
    if [[ -n "$OLD_PID" ]] && kill -0 "$OLD_PID" 2>/dev/null; then
        log "Defrag already running (PID $OLD_PID). Exiting."
        exit 0
    fi
fi
echo "$$" > "$DEFRAG_LOCK"
trap 'rm -f "$DEFRAG_LOCK"; log "Defrag interrupted."' EXIT INT TERM

# ---- Verify mount -----------------------------------------------------------
if ! mountpoint -q "$MOUNT_POINT"; then
    error "$MOUNT_POINT is not mounted. Cannot defrag."
    exit 1
fi

FS_TYPE=$(findmnt -n -o FSTYPE "$MOUNT_POINT" 2>/dev/null || echo "")
if [[ "$FS_TYPE" != "btrfs" ]]; then
    error "$MOUNT_POINT is not a BTRFS filesystem (found: $FS_TYPE)."
    exit 1
fi

log "===== BTRFS Defrag Started ====="
log "Host: $HOSTNAME | Mount: $MOUNT_POINT"

# ---- Defrag small files (< 64K) first, then large files --------------------
RESULTS=""
OVERALL_STATUS="ok"
TOTAL_FILES=0

defrag_path() {{
    local path="$1"
    local label="$2"
    local extra_flags="${{3:-}}"

    log "Defragmenting $label: $path"

    local tmp_log
    tmp_log=$(mktemp)
    local start_t=$SECONDS

    # -r = recursive, -v = verbose, -czstd = compress with zstd
    if btrfs filesystem defragment -r -v -czstd $extra_flags "$path" > "$tmp_log" 2>&1; then
        local duration=$((SECONDS - start_t))
        local file_count
        file_count=$(wc -l < "$tmp_log" || echo "0")
        TOTAL_FILES=$((TOTAL_FILES + file_count))
        log "  ✓ $label completed in ${{duration}}s (${{file_count}} files)"
        RESULTS+="PATH:$path|LABEL:$label|STATUS:ok|DURATION:${{duration}}s|FILES:$file_count\\n"
    else
        local duration=$((SECONDS - start_t))
        log "  ✗ $label failed after ${{duration}}s"
        OVERALL_STATUS="warning"
        RESULTS+="PATH:$path|LABEL:$label|STATUS:failed|DURATION:${{duration}}s|FILES:0\\n"
    fi

    rm -f "$tmp_log"
    cat "$LOG_FILE" >> "$LOG_FILE" 2>/dev/null || true
}}

# Defrag the main data mount
defrag_path "$MOUNT_POINT" "main-data"

# Defrag any subvolumes
while IFS= read -r subvol; do
    subvol_path="$MOUNT_POINT/$subvol"
    if [[ -d "$subvol_path" ]]; then
        defrag_path "$subvol_path" "subvol:$subvol"
    fi
done < <(btrfs subvolume list "$MOUNT_POINT" 2>/dev/null | awk '{{print $NF}}' || true)

END_TIME="$(date '+%Y-%m-%d %H:%M:%S')"
log "Total files defragmented: $TOTAL_FILES"
log "Overall status: $OVERALL_STATUS"
log "===== Defrag Complete ====="

# ---- Clean up done file so next month's cycle works cleanly ----------------
rm -f "$SMART_DONE_FILE"

# ---- Send email report ------------------------------------------------------
if command -v python3 &>/dev/null; then
    python3 - <<PYEOF
import sys
sys.path.insert(0, "${{SUITE_DIR}}")
from core.notifications import NotificationManager
from pathlib import Path

nm = NotificationManager(Path("${{SUITE_DIR}}"))
raw = r\"\"\"{RESULTS}\"\"\"
results = []
for line in raw.strip().splitlines():
    if not line.strip():
        continue
    d = {{}}
    for part in line.split("|"):
        if ":" in part:
            k, _, v = part.partition(":")
            d[k.lower()] = v
    if d:
        results.append(d)

html = nm.render_defrag_report(results, "${{HOSTNAME}}")
subject = f"BTRFS Defrag: ${{OVERALL_STATUS.upper()}} — ${{HOSTNAME}}"
nm.send_report(subject, html, recipient="${{NOTIFY_EMAIL}}")
print("Email report sent.")
PYEOF
fi

rm -f "$DEFRAG_LOCK"
[[ "$OVERALL_STATUS" == "ok" ]] && exit 0 || exit 1
"""
        _write(self.scripts_dir / "btrfs-defrag.sh", script, mode=0o750)
        console.print("  [dim]Generated: btrfs-defrag.sh ✓[/dim]")

    # -----------------------------------------------------------------------
    # BTRFS scrub script
    # -----------------------------------------------------------------------

    def _generate_btrfs_scrub(self, config: dict):
        """Generate the BTRFS scrub script (data integrity check)."""
        mount_point = config.get("storage", {}).get("mount_point", "/mnt/data")
        script = f"""#!/usr/bin/env bash
# =============================================================================
# Server Suite — BTRFS Scrub (Data Integrity Verification)
# Scrub reads all data and verifies checksums — different from defrag.
# Runs on day 8 of each month (after defrag window clears).
# =============================================================================
set -euo pipefail

SUITE_DIR="{self.suite_dir}"
MOUNT_POINT="{mount_point}"
LOG_FILE="{LOG_DIR}/btrfs-scrub.log"
NOTIFY_EMAIL="{self.notify_email}"
HOSTNAME="$(hostname -f)"

log() {{ echo "[$( date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"; }}

mkdir -p "{LOG_DIR}"

if ! mountpoint -q "$MOUNT_POINT"; then
    log "ERROR: $MOUNT_POINT not mounted."
    exit 1
fi

log "===== BTRFS Scrub Started ====="
log "Host: $HOSTNAME | Mount: $MOUNT_POINT"

# Start scrub (blocking — waits for completion)
if btrfs scrub start -B "$MOUNT_POINT" >> "$LOG_FILE" 2>&1; then
    STATUS="PASSED"
    log "Scrub completed successfully."
else
    STATUS="FAILED"
    log "ERROR: Scrub reported errors — check $LOG_FILE"
fi

# Get scrub stats
STATS=$(btrfs scrub status "$MOUNT_POINT" 2>/dev/null || echo "Stats unavailable")
log "Scrub stats: $STATS"
log "===== BTRFS Scrub Complete: $STATUS ====="

# Send report
if command -v python3 &>/dev/null; then
    python3 - <<PYEOF
import sys
sys.path.insert(0, "${{SUITE_DIR}}")
from core.notifications import NotificationManager
from pathlib import Path

nm = NotificationManager(Path("${{SUITE_DIR}}"))
results = [{{"path": "${{MOUNT_POINT}}", "label": "scrub", "status": "${{STATUS}}".lower(),
             "duration": "see log", "files_processed": "N/A"}}]
html = nm.render_defrag_report(results, "${{HOSTNAME}}")
nm.send_report(f"BTRFS Scrub: ${{STATUS}} — ${{HOSTNAME}}", html,
               recipient="${{NOTIFY_EMAIL}}")
PYEOF
fi

[[ "$STATUS" == "PASSED" ]] && exit 0 || exit 2
"""
        _write(self.scripts_dir / "btrfs-scrub.sh", script, mode=0o750)
        console.print("  [dim]Generated: btrfs-scrub.sh ✓[/dim]")

    # -----------------------------------------------------------------------
    # Health check script
    # -----------------------------------------------------------------------

    def _generate_health_check(self):
        """Generate daily health check script."""
        script = f"""#!/usr/bin/env bash
# =============================================================================
# Server Suite — Daily Health Check
# Checks: disk temperatures, disk space thresholds, BTRFS/RAID status,
#         failed systemd services, Docker container health.
# Sends alert email only when thresholds are breached.
# =============================================================================
set -euo pipefail

SUITE_DIR="{self.suite_dir}"
LOG_FILE="{LOG_DIR}/health-check.log"
NOTIFY_EMAIL="{self.notify_email}"
HOSTNAME="$(hostname -f)"
ALERTS=()
TEMP_THRESHOLD=55
SPACE_WARN_PCT=75
SPACE_CRIT_PCT=90

log() {{ echo "[$( date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"; }}

mkdir -p "{LOG_DIR}"
log "===== Health Check Started ====="

# ---- Disk temperatures ------------------------------------------------------
while IFS= read -r dev; do
    TEMP=$(smartctl -A "$dev" 2>/dev/null | grep -E "^[[:space:]]*(190|194)[[:space:]]" | awk '{{print $NF}}' | head -1 || echo "")
    if [[ -n "$TEMP" ]] && [[ "$TEMP" -gt "$TEMP_THRESHOLD" ]] 2>/dev/null; then
        ALERTS+=("HIGH TEMP: $dev is at ${{TEMP}}°C (threshold: ${{TEMP_THRESHOLD}}°C)")
        log "WARNING: $dev temperature ${{TEMP}}°C exceeds threshold"
    fi
done < <(lsblk -d -o NAME,TYPE --noheadings | awk '$2=="disk" {{print "/dev/"$1}}')

# ---- Disk space -------------------------------------------------------------
while IFS= read -r line; do
    PCT=$(echo "$line" | awk '{{print $5}}' | tr -d '%')
    MOUNT=$(echo "$line" | awk '{{print $6}}')
    if [[ "$PCT" -ge "$SPACE_CRIT_PCT" ]] 2>/dev/null; then
        ALERTS+=("CRITICAL DISK SPACE: $MOUNT is ${{PCT}}% full")
        log "CRITICAL: $MOUNT at ${{PCT}}%"
    elif [[ "$PCT" -ge "$SPACE_WARN_PCT" ]] 2>/dev/null; then
        ALERTS+=("LOW DISK SPACE: $MOUNT is ${{PCT}}% full")
        log "WARNING: $MOUNT at ${{PCT}}%"
    fi
done < <(df -h | grep -v "^Filesystem" | grep -v "tmpfs" | grep -v "udev")

# ---- BTRFS health -----------------------------------------------------------
for BTRFS_MOUNT in $(findmnt -t btrfs -o TARGET --noheadings 2>/dev/null); do
    ERRORS=$(btrfs device stats "$BTRFS_MOUNT" 2>/dev/null | grep -v " 0$" || true)
    if [[ -n "$ERRORS" ]]; then
        ALERTS+=("BTRFS ERRORS on $BTRFS_MOUNT: $(echo "$ERRORS" | head -3)")
        log "WARNING: BTRFS errors on $BTRFS_MOUNT"
    fi
done

# ---- Failed systemd services ------------------------------------------------
FAILED=$(systemctl --failed --no-legend 2>/dev/null | awk '{{print $1}}' | head -5 || true)
if [[ -n "$FAILED" ]]; then
    ALERTS+=("FAILED SERVICES: $FAILED")
    log "WARNING: Failed services: $FAILED"
fi

# ---- Docker container health ------------------------------------------------
if command -v docker &>/dev/null; then
    UNHEALTHY=$(docker ps --filter "health=unhealthy" --format "{{{{.Names}}}}" 2>/dev/null || true)
    if [[ -n "$UNHEALTHY" ]]; then
        ALERTS+=("UNHEALTHY CONTAINERS: $UNHEALTHY")
        log "WARNING: Unhealthy containers: $UNHEALTHY"
    fi
fi

# ---- RAID degradation check (mdadm) ----------------------------------------
if command -v mdadm &>/dev/null; then
    DEGRADED=$(cat /proc/mdstat 2>/dev/null | grep -i "degraded" || true)
    if [[ -n "$DEGRADED" ]]; then
        ALERTS+=("RAID DEGRADED: $DEGRADED")
        log "CRITICAL: RAID array degraded!"
    fi
fi

log "Health check complete. Alerts: ${{#ALERTS[@]}}"

# ---- Send alerts if any found -----------------------------------------------
if [[ ${{#ALERTS[@]}} -gt 0 ]]; then
    log "Sending alert email..."
    python3 - <<PYEOF
import sys
sys.path.insert(0, "${{SUITE_DIR}}")
from core.notifications import NotificationManager
from pathlib import Path

alerts = [
$(printf '    "%s",\n' "${{ALERTS[@]}}")
]

nm = NotificationManager(Path("${{SUITE_DIR}}"))
details = {{f"Alert {{i+1}}": a for i, a in enumerate(alerts)}}
html = nm.render_health_alert("Daily Health Check", details, "${{HOSTNAME}}")
nm.send_report(f"⚠ Health Alert (${{len(alerts)}} issue(s)) — ${{HOSTNAME}}",
               html, recipient="${{NOTIFY_EMAIL}}")
print(f"Alert email sent: {{len(alerts)}} issues.")
PYEOF
else
    log "All health checks passed — no alerts."
fi

log "===== Health Check Complete ====="
"""
        _write(self.scripts_dir / "health-check.sh", script, mode=0o750)
        console.print("  [dim]Generated: health-check.sh ✓[/dim]")

    # -----------------------------------------------------------------------
    # Systemd unit files
    # -----------------------------------------------------------------------

    def _install_smart_timer(self):
        """SMART scan — runs at 22:00 on day 1 of each month."""

        service = """[Unit]
Description=Server Suite — SMART Long Disk Scan
Documentation=https://github.com/server-suite
After=network.target
Wants=server-suite-smart-scan.timer

[Service]
Type=oneshot
ExecStart=/opt/server-suite/scripts/smart-scan.sh
TimeoutStartSec=28800
StandardOutput=journal
StandardError=journal
SyslogIdentifier=server-suite-smart
# Notify on failure
OnFailure=server-suite-notify-failure@%n.service

[Install]
WantedBy=multi-user.target
"""

        timer = """[Unit]
Description=Server Suite — SMART Scan Timer (Monthly, day 1 at 22:00)
Documentation=https://github.com/server-suite

[Timer]
# Run at 22:00 on the 1st of every month
OnCalendar=*-*-01 22:00:00
# If system was off when timer fired, run within 30 minutes of next boot
Persistent=true
# Random delay up to 5 minutes to avoid thundering herd
RandomizedDelaySec=300
Unit=server-suite-smart-scan.service

[Install]
WantedBy=timers.target
"""
        _write(SYSTEMD_DIR / "server-suite-smart-scan.service", service)
        _write(SYSTEMD_DIR / "server-suite-smart-scan.timer",   timer)
        console.print("  [dim]Installed: SMART scan timer (monthly, day 1 @ 22:00) ✓[/dim]")

    def _install_defrag_timer(self):
        """BTRFS defrag — runs at 22:00 on day 1 of each month (after SMART)."""

        service = """[Unit]
Description=Server Suite — BTRFS Defragmentation
Documentation=https://github.com/server-suite
After=network.target server-suite-smart-scan.service
Wants=server-suite-btrfs-defrag.timer

[Service]
Type=oneshot
ExecStart=/opt/server-suite/scripts/btrfs-defrag.sh
TimeoutStartSec=43200
StandardOutput=journal
StandardError=journal
SyslogIdentifier=server-suite-defrag

[Install]
WantedBy=multi-user.target
"""

        timer = """[Unit]
Description=Server Suite — BTRFS Defrag Timer (Monthly, day 1 at 22:00, after SMART)
Documentation=https://github.com/server-suite

[Timer]
# Same day as SMART scan — the defrag script handles the dependency check
# and will reschedule itself if SMART is still running past 06:00
OnCalendar=*-*-01 22:00:00
Persistent=true
RandomizedDelaySec=600
Unit=server-suite-btrfs-defrag.service

[Install]
WantedBy=timers.target
"""
        _write(SYSTEMD_DIR / "server-suite-btrfs-defrag.service", service)
        _write(SYSTEMD_DIR / "server-suite-btrfs-defrag.timer",   timer)
        console.print("  [dim]Installed: BTRFS defrag timer (monthly, day 1 @ 22:00) ✓[/dim]")

    def _install_defrag_catchup_timer(self):
        """
        Catch-up timer: activated by the defrag script when SMART ran past 06:00.
        Fires once at 22:00 the same evening it's activated.
        """
        service = """[Unit]
Description=Server Suite — BTRFS Defrag Catch-Up (runs tonight at 22:00)
Documentation=https://github.com/server-suite

[Service]
Type=oneshot
ExecStart=/opt/server-suite/scripts/btrfs-defrag.sh
TimeoutStartSec=43200
StandardOutput=journal
StandardError=journal
SyslogIdentifier=server-suite-defrag-catchup
"""

        timer = """[Unit]
Description=Server Suite — BTRFS Defrag Catch-Up Timer (tonight at 22:00)
Documentation=https://github.com/server-suite

[Timer]
# This is a one-shot timer — activated on-demand by the defrag script
# when SMART scan is still running at 06:00
OnCalendar=*-*-* 22:00:00
# Only fire once — not persistent across reboots
Persistent=false
Unit=server-suite-btrfs-defrag-catchup.service

[Install]
WantedBy=timers.target
"""
        _write(SYSTEMD_DIR / "server-suite-btrfs-defrag-catchup.service", service)
        _write(SYSTEMD_DIR / "server-suite-btrfs-defrag-catchup.timer",   timer)
        console.print("  [dim]Installed: BTRFS defrag catch-up timer ✓[/dim]")

    def _install_scrub_timer(self):
        """BTRFS scrub — runs at 22:00 on day 8 of each month."""

        service = """[Unit]
Description=Server Suite — BTRFS Scrub (Data Integrity Verification)
Documentation=https://github.com/server-suite
After=network.target

[Service]
Type=oneshot
ExecStart=/opt/server-suite/scripts/btrfs-scrub.sh
TimeoutStartSec=86400
StandardOutput=journal
StandardError=journal
SyslogIdentifier=server-suite-scrub
"""

        timer = """[Unit]
Description=Server Suite — BTRFS Scrub Timer (Monthly, day 8 at 22:00)
Documentation=https://github.com/server-suite

[Timer]
OnCalendar=*-*-08 22:00:00
Persistent=true
RandomizedDelaySec=300
Unit=server-suite-btrfs-scrub.service

[Install]
WantedBy=timers.target
"""
        _write(SYSTEMD_DIR / "server-suite-btrfs-scrub.service", service)
        _write(SYSTEMD_DIR / "server-suite-btrfs-scrub.timer",   timer)
        console.print("  [dim]Installed: BTRFS scrub timer (monthly, day 8 @ 22:00) ✓[/dim]")

    def _install_health_check_timer(self):
        """Daily health check at 08:00."""

        service = """[Unit]
Description=Server Suite — Daily Health Check
Documentation=https://github.com/server-suite
After=network.target

[Service]
Type=oneshot
ExecStart=/opt/server-suite/scripts/health-check.sh
TimeoutStartSec=600
StandardOutput=journal
StandardError=journal
SyslogIdentifier=server-suite-health
"""

        timer = """[Unit]
Description=Server Suite — Daily Health Check Timer (08:00 daily)
Documentation=https://github.com/server-suite

[Timer]
OnCalendar=*-*-* 08:00:00
Persistent=true
RandomizedDelaySec=300
Unit=server-suite-health-check.service

[Install]
WantedBy=timers.target
"""
        _write(SYSTEMD_DIR / "server-suite-health-check.service", service)
        _write(SYSTEMD_DIR / "server-suite-health-check.timer",   timer)
        console.print("  [dim]Installed: Health check timer (daily @ 08:00) ✓[/dim]")

    # -----------------------------------------------------------------------
    # Failure notification unit (generic)
    # -----------------------------------------------------------------------

    def _install_failure_notify_unit(self):
        """Generic failure notification service used by OnFailure= directives."""
        service = f"""[Unit]
Description=Server Suite — Service Failure Notification for %i

[Service]
Type=oneshot
ExecStart=/bin/bash -c 'python3 {self.suite_dir}/maintenance/notify_failure.py "%i"'
"""
        _write(SYSTEMD_DIR / "server-suite-notify-failure@.service", service)

    # -----------------------------------------------------------------------
    # Log rotation
    # -----------------------------------------------------------------------

    def _configure_logrotate(self):
        """Write logrotate config for all suite logs."""
        logrotate_conf = f"""{LOG_DIR}/*.log {{
    weekly
    rotate 12
    compress
    delaycompress
    missingok
    notifempty
    create 640 root root
    sharedscripts
    postrotate
        systemctl reload rsyslog 2>/dev/null || true
    endscript
}}
"""
        _write(Path("/etc/logrotate.d/server-suite"), logrotate_conf)
        console.print("  [dim]Configured logrotate ✓[/dim]")

    # -----------------------------------------------------------------------
    # Enable timers
    # -----------------------------------------------------------------------

    def _enable_timers(self, has_storage: bool):
        timers = ["server-suite-health-check.timer"]
        if has_storage:
            timers += [
                "server-suite-smart-scan.timer",
                "server-suite-btrfs-defrag.timer",
                "server-suite-btrfs-scrub.timer",
            ]
            # NOTE: catchup timer is NOT enabled at boot — activated on-demand
        for timer in timers:
            rc, _, err = _run(["systemctl", "enable", "--now", timer])
            if rc != 0:
                console.print(f"  [yellow]Warning: Could not enable {timer}: {err}[/yellow]")
            else:
                console.print(f"  [dim]Enabled: {timer} ✓[/dim]")

    # -----------------------------------------------------------------------
    # Summary
    # -----------------------------------------------------------------------

    def _print_schedule_summary(self, has_storage: bool):
        from rich.table import Table
        table = Table(
            "Unit", "Schedule", "Purpose",
            show_header=True,
            header_style="bold magenta",
            border_style="dim"
        )
        table.add_row("health-check",     "Daily    @ 08:00",              "Disk temp, space, container health")
        if has_storage:
            table.add_row("smart-scan",       "Monthly  — day  1 @ 22:00",     "SMART long test on all drives")
            table.add_row("btrfs-defrag",     "Monthly  — day  1 @ 22:00+",    "BTRFS defrag (after SMART completes)")
            table.add_row("btrfs-defrag",     "Catch-up — tonight @ 22:00",    "If SMART ran past 06:00")
            table.add_row("btrfs-scrub",      "Monthly  — day  8 @ 22:00",     "BTRFS data integrity scrub")
        console.print(table)
        console.print()
        console.print("  [dim]All units log to /var/log/server-suite/ and systemd journal.[/dim]")
        console.print("  [dim]Email reports sent to:[/dim] " + f"[cyan]{self.notify_email}[/cyan]")
