"""
setup_ui/roles_config.py
========================
ROLES dict extracted for testing and CLI use without Flask dependency.
Auto-generated — do not edit. Edit setup_ui/app.py instead.
"""

ROLES = {
    "storage": {
        "name": "Storage & Backup",
        "icon": "🗄️",
        "description": "BTRFS RAID, SMART monitoring, automated backups with BorgBackup and rclone.",
        "min_ram_gb": 1,
        "min_cores": 1,
        "docker": False,
        "sub_options": ["btrfs_raid", "smart_monitoring", "borgbackup", "rclone_offsite"],
        "conflicts": [],
        "requires": [],
    },
    "web": {
        "name": "Web Server",
        "icon": "🌐",
        "description": "Nginx Proxy Manager, OpenLiteSpeed, or Apache2 with automatic TLS certificates.",
        "min_ram_gb": 1,
        "min_cores": 1,
        "docker": True,
        "sub_options": ["nginx_proxy_manager", "traefik", "openlitespeed", "apache2"],
        "conflicts": [],
        "requires": [],
    },
    "mail": {
        "name": "Mail Server",
        "icon": "📧",
        "description": "Mailcow: fully-featured mail server with SOGo webmail, spam filtering, DKIM/DMARC.",
        "min_ram_gb": 3,
        "min_cores": 2,
        "docker": True,
        "sub_options": ["mailcow"],
        "conflicts": [],
        "requires": ["web"],
    },
    "identity": {
        "name": "Identity & Directory",
        "icon": "🏛️",
        "description": (
            "FreeIPA: Kerberos KDC, 389 Directory Server, Dogtag PKI CA, "
            "integrated BIND DNS, HBAC, sudo policies, and web UI. "
            "Replaces standalone DNS/DHCP when integrated DNS is enabled."
        ),
        "min_ram_gb": 2,
        "min_cores": 2,
        "docker": False,
        "sub_options": ["freeipa", "samba_ad"],
        "conflicts": [],
        "requires": [],
        "suppresses_if_dns": ["dns_dhcp"],
    },
    "dns_dhcp": {
        "name": "DNS & DHCP",
        "icon": "🔍",
        "description": "Technitium (recommended), BIND9, or FreeIPA-managed DNS with optional DHCP.",
        "min_ram_gb": 0.5,
        "min_cores": 1,
        "docker": True,
        "sub_options": ["technitium", "bind9", "kea_dhcp"],
        "conflicts": [],
        "requires": [],
    },
    "database": {
        "name": "Database Server",
        "icon": "🗃️",
        "description": "MariaDB, PostgreSQL, Redis with Adminer web management interface.",
        "min_ram_gb": 1,
        "min_cores": 1,
        "docker": True,
        "sub_options": ["mariadb", "postgresql", "redis", "adminer"],
        "conflicts": [],
        "requires": [],
    },
    "files": {
        "name": "File Sharing & Collaboration",
        "icon": "📁",
        "description": "Nextcloud with Talk, Calendar, Contacts, and optional Collabora/OnlyOffice.",
        "min_ram_gb": 2,
        "min_cores": 2,
        "docker": True,
        "sub_options": ["nextcloud", "collabora", "onlyoffice", "samba_shares", "nfs", "syncthing"],
        "conflicts": [],
        "requires": ["web", "database"],
    },
    "comms": {
        "name": "Communication Server",
        "icon": "💬",
        "description": "Matrix/Synapse + Element, Jitsi Meet, Mattermost, or Mumble.",
        "min_ram_gb": 2,
        "min_cores": 2,
        "docker": True,
        "sub_options": ["matrix", "jitsi", "mattermost", "mumble"],
        "conflicts": [],
        "requires": ["web", "database"],
    },
    "vpn": {
        "name": "VPN Server",
        "icon": "🔒",
        "description": "WireGuard (recommended) or OpenVPN with web management interface.",
        "min_ram_gb": 0.5,
        "min_cores": 1,
        "docker": True,
        "sub_options": ["wireguard", "openvpn"],
        "conflicts": [],
        "requires": [],
    },
    "security": {
        "name": "Security Monitoring",
        "icon": "🛡️",
        "description": "Wazuh HIDS: threat detection, compliance monitoring, log analysis, security dashboard.",
        "min_ram_gb": 4,
        "min_cores": 4,
        "docker": True,
        "sub_options": ["wazuh_server", "wazuh_agent_only"],
        "conflicts": [],
        "requires": [],
    },
    "logging": {
        "name": "Logging & Metrics",
        "icon": "📊",
        "description": "Graylog, Loki+Grafana, or Prometheus+Grafana for centralized logging and metrics.",
        "min_ram_gb": 2,
        "min_cores": 2,
        "docker": True,
        "sub_options": ["graylog", "loki_grafana", "prometheus_grafana"],
        "conflicts": [],
        "requires": [],
    },
}
